### ISSUE TITLE
how do you type up your beautiful posts

### ISSUE THREAD

**Issue by yasserius** [yashbonde/yashbonde.github.io#2]
Hi Yash,

Love your notes from Sutton and Barto, finding them very helpful.

How do you type up and style your beautiful articles?

Is it possible with jupyter notebooks?

Thanks in advance!

**Comment by yashbonde** [comment]
Thank you for your interest in my blogs.
I used to be a graphics designer in my college days, so I took up writing CSS and website as a challenge. You can find the code in the repo. I tried to convert the markdown so I could upload it here but didn't work out as planned.
However these days I am using [streamlit](https://www.streamlit.io/) as my goto FE platform, allows things to be interactive unlike Jupyter Notebooks and can be uploaded as a webapp on heroku and other cloud providers.

**Comment by yasserius** [comment]
Thanks, I will use your css and also check out steamlit
